//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITWBackup.Lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITWBackup.Lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel selected! ähnelt.
        /// </summary>
        internal static string Abbruch {
            get {
                return ResourceManager.GetString("Abbruch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Canceled! ähnelt.
        /// </summary>
        internal static string Aktionabgebrochen {
            get {
                return ResourceManager.GetString("Aktionabgebrochen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die on ähnelt.
        /// </summary>
        internal static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Directory ähnelt.
        /// </summary>
        internal static string Backupverzeichnis {
            get {
                return ResourceManager.GetString("Backupverzeichnis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR! \r\nThe selected \n\ruser data \n\rcould not be copied.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string BEN {
            get {
                return ResourceManager.GetString("BEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No User Data had been selected ähnelt.
        /// </summary>
        internal static string BEN2 {
            get {
                return ResourceManager.GetString("BEN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string Beschreibung {
            get {
                return ResourceManager.GetString("Beschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        internal static string btnEnde {
            get {
                return ResourceManager.GetString("btnEnde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deselect File ähnelt.
        /// </summary>
        internal static string btnEntfernen {
            get {
                return ResourceManager.GetString("btnEntfernen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear File List ähnelt.
        /// </summary>
        internal static string btnListeleeren {
            get {
                return ResourceManager.GetString("btnListeleeren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Forms ähnelt.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activate ähnelt.
        /// </summary>
        internal static string btnSetzen {
            get {
                return ResourceManager.GetString("btnSetzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start the Backup ähnelt.
        /// </summary>
        internal static string btnStarten {
            get {
                return ResourceManager.GetString("btnStarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Backup Directory ähnelt.
        /// </summary>
        internal static string btnVerzeichnis {
            get {
                return ResourceManager.GetString("btnVerzeichnis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The backup will be ähnelt.
        /// </summary>
        internal static string BWillBe {
            get {
                return ResourceManager.GetString("BWillBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Perform the backup later ähnelt.
        /// </summary>
        internal static string chkspaeter {
            get {
                return ResourceManager.GetString("chkspaeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        internal static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die be performed. ähnelt.
        /// </summary>
        internal static string ExecutionLabel {
            get {
                return ResourceManager.GetString("ExecutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die found. ähnelt.
        /// </summary>
        internal static string Gefunden {
            get {
                return ResourceManager.GetString("Gefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected Path: ähnelt.
        /// </summary>
        internal static string gewaehlterPfad {
            get {
                return ResourceManager.GetString("gewaehlterPfad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR! \r\nThe File HardC.ini \r\ncouldn&apos;t be copied.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HardC.ini exists.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string HardCgefunden {
            get {
                return ResourceManager.GetString("HardCgefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HardC.ini hasn&apos;t been \nlocated.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string HardCnichtgefunden {
            get {
                return ResourceManager.GetString("HardCnichtgefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR! \r\nThe File HMData.mdb \r\ncouldn&apos;t be copied.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string HMD {
            get {
                return ResourceManager.GetString("HMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HMData.mdb exists.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string HMDatagefunden {
            get {
                return ResourceManager.GetString("HMDatagefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HMData.mdb hasn&apos;t been \nlocated.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string HMDatanichtgefunden {
            get {
                return ResourceManager.GetString("HMDatanichtgefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die has been copied\r\nsuccessfully\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string Kopiert {
            get {
                return ResourceManager.GetString("Kopiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string languageToolStripMenuItem {
            get {
                return ResourceManager.GetString("languageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup the user data from last time as well? ähnelt.
        /// </summary>
        internal static string loadfiles {
            get {
                return ResourceManager.GetString("loadfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User data load ähnelt.
        /// </summary>
        internal static string loadfilestitle {
            get {
                return ResourceManager.GetString("loadfilestitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Path: ähnelt.
        /// </summary>
        internal static string neuerPfad {
            get {
                return ResourceManager.GetString("neuerPfad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hasn&apos;t been found ähnelt.
        /// </summary>
        internal static string NichtGefunden {
            get {
                return ResourceManager.GetString("NichtGefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die couldn&apos;t be copied.\n ERROR!\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string NichtKopiert {
            get {
                return ResourceManager.GetString("NichtKopiert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die every \r\n28 Days ähnelt.
        /// </summary>
        internal static string OurMonthly {
            get {
                return ResourceManager.GetString("OurMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weekly \r\nonce ähnelt.
        /// </summary>
        internal static string OurWeekly {
            get {
                return ResourceManager.GetString("OurWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yearly \r\non ähnelt.
        /// </summary>
        internal static string OurYearly {
            get {
                return ResourceManager.GetString("OurYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program Files Path: ähnelt.
        /// </summary>
        internal static string programmePfad {
            get {
                return ResourceManager.GetString("programmePfad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup custom selected Dirs ähnelt.
        /// </summary>
        internal static string radBenutzer {
            get {
                return ResourceManager.GetString("radBenutzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup HardC.ini only ähnelt.
        /// </summary>
        internal static string radHardC {
            get {
                return ResourceManager.GetString("radHardC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup HMData.mdb only ähnelt.
        /// </summary>
        internal static string radHMData {
            get {
                return ResourceManager.GetString("radHMData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secure HMData &amp; VidEqu.Cfg ähnelt.
        /// </summary>
        internal static string radHMVid {
            get {
                return ResourceManager.GetString("radHMVid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Complete Backup ähnelt.
        /// </summary>
        internal static string radKomplett {
            get {
                return ResourceManager.GetString("radKomplett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die monthly ähnelt.
        /// </summary>
        internal static string radMonthly {
            get {
                return ResourceManager.GetString("radMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die once ähnelt.
        /// </summary>
        internal static string radOnce {
            get {
                return ResourceManager.GetString("radOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup VidEqu.Cfg only ähnelt.
        /// </summary>
        internal static string radVidEqu {
            get {
                return ResourceManager.GetString("radVidEqu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weekly ähnelt.
        /// </summary>
        internal static string radWeekly {
            get {
                return ResourceManager.GetString("radWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup WinCon &amp; WinCon2 only ähnelt.
        /// </summary>
        internal static string radWinCon {
            get {
                return ResourceManager.GetString("radWinCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die yearly ähnelt.
        /// </summary>
        internal static string radYearly {
            get {
                return ResourceManager.GetString("radYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backup Size ähnelt.
        /// </summary>
        internal static string sichergroesse {
            get {
                return ResourceManager.GetString("sichergroesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EN ähnelt.
        /// </summary>
        internal static string sprache {
            get {
                return ResourceManager.GetString("sprache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success! ähnelt.
        /// </summary>
        internal static string SuccessLabel {
            get {
                return ResourceManager.GetString("SuccessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Backup will be ähnelt.
        /// </summary>
        internal static string TheBackup {
            get {
                return ResourceManager.GetString("TheBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The date ähnelt.
        /// </summary>
        internal static string TheBDate {
            get {
                return ResourceManager.GetString("TheBDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commands ähnelt.
        /// </summary>
        internal static string txtgrpButtonage {
            get {
                return ResourceManager.GetString("txtgrpButtonage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag &amp;&amp; Drop Files in here ähnelt.
        /// </summary>
        internal static string txtgrpDragDrop {
            get {
                return ResourceManager.GetString("txtgrpDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string txtgrpOptions {
            get {
                return ResourceManager.GetString("txtgrpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die custom data ähnelt.
        /// </summary>
        internal static string UserFileData {
            get {
                return ResourceManager.GetString("UserFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is a Directory ähnelt.
        /// </summary>
        internal static string Verzeichnis {
            get {
                return ResourceManager.GetString("Verzeichnis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory Size: ähnelt.
        /// </summary>
        internal static string verzgroesse {
            get {
                return ResourceManager.GetString("verzgroesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR! \r\nThe File VidEqu.Cfg \r\ncouldn&apos;t be copied.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string VID {
            get {
                return ResourceManager.GetString("VID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Videqu.Cfg exists.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string VidEqugefunden {
            get {
                return ResourceManager.GetString("VidEqugefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Videqu.Cfg hasn&apos;t been \nlocated.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string VidEqunichtgefunden {
            get {
                return ResourceManager.GetString("VidEqunichtgefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR! \r\nCouldn&apos;t copy \r\nC:\\WinCon \r\nThere has been an Error.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string WCK {
            get {
                return ResourceManager.GetString("WCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERROR! \r\nCouldn&apos;t copy \r\nC:\\Program Files\\WinCon \r\nThere has been an Error.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string WCK2 {
            get {
                return ResourceManager.GetString("WCK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WinCon2 found.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string WinCon2gefunden {
            get {
                return ResourceManager.GetString("WinCon2gefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WinCon2 \ncouldn&apos;t be found.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string WinCon2nichtgefunden {
            get {
                return ResourceManager.GetString("WinCon2nichtgefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WinCon found.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string WinCongefunden {
            get {
                return ResourceManager.GetString("WinCongefunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wincon \ncouldn&apos;t be found.\r\n---------------------------------------------- ähnelt.
        /// </summary>
        internal static string WinConnichtgefunden {
            get {
                return ResourceManager.GetString("WinConnichtgefunden", resourceCulture);
            }
        }
    }
}
